# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_amenity_dailymenuitem_dailymessmenu_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='allocation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Allocation Date'),
        ),
        migrations.AlterField(
            model_name='hostelattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
