# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypolicy',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Effective Date'),
        ),
    ]
