# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_budgettemplateitem_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='as_of_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Balance As Of'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Issue Date'),
        ),
    ]
