# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='housepoints',
            name='date_awarded',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date Awarded'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
