# Generated by Django 4.2.7 on 2025-12-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_payments_enabled', models.BooleanField(default=False, verbose_name='Enable Payments')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razorpay Key ID')),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razorpay Key Secret')),
                ('stripe_public_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Public Key')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Secret Key')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Payment Currency')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='Test Mode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configuration', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'db_table': 'tenant_payment_configurations',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Analytics ID')),
                ('clarity_project_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clarity Project ID')),
                ('anonymize_ip', models.BooleanField(default=True, verbose_name='Anonymize IP Addresses')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_configuration', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Analytics Configuration',
                'db_table': 'tenant_analytics_configurations',
            },
        ),
    ]
