# Generated by Django 4.2.7 on 2025-12-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Onboarding Status'),
        ),
    ]
