# Generated by Django 4.2.7 on 2025-12-24 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_tenant_onboarding_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('mistral', 'Mistral AI'), ('llama', 'Meta Llama'), ('whatsapp', 'WhatsApp Business'), ('twilio', 'Twilio (General)'), ('twilio_sms', 'Twilio SMS'), ('twilio_voice', 'Twilio Voice'), ('twilio_video', 'Twilio Video'), ('cloudinary', 'Cloudinary'), ('aws_s3', 'AWS S3'), ('aws_rekognition', 'AWS Rekognition'), ('aws_polly', 'AWS Polly'), ('aws_transcribe', 'AWS Transcribe'), ('google_vision', 'Google Vision'), ('google_speech', 'Google Speech'), ('google_translate', 'Google Translate'), ('azure_ai', 'Azure AI'), ('azure_speech', 'Azure Speech'), ('azure_vision', 'Azure Vision'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('google_maps', 'Google Maps'), ('sms_gateway', 'SMS Gateway'), ('email_gateway', 'Email Gateway'), ('push_notification', 'Push Notification')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('base_url', models.URLField(blank=True, help_text='Base API URL')),
                ('documentation_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=True)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('jwt', 'JWT'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token')], default='api_key', max_length=20)),
                ('default_rate_limit', models.PositiveIntegerField(default=100, help_text='Requests per minute')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('config_schema', models.JSONField(default=dict, help_text='Configuration JSON schema')),
            ],
            options={
                'verbose_name': 'API Service',
                'verbose_name_plural': 'API Services',
                'db_table': 'api_services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('name', models.CharField(help_text='Display name for this key', max_length=100)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=500, verbose_name='API Key/Client ID'))),
                ('api_secret', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='API Secret/Client Secret'))),
                ('access_token', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('refresh_token', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('config', models.JSONField(default=dict, help_text='Service-specific configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default for this service')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test/sandbox environment')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100)),
                ('rate_limit_per_day', models.PositiveIntegerField(default=10000)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_keys', to='tenants.apiservice', verbose_name='API Service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Tenant API Key',
                'verbose_name_plural': 'Tenant API Keys',
                'db_table': 'tenant_api_keys',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('response_time_ms', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('response_size_bytes', models.PositiveIntegerField(default=0)),
                ('cost_units', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='tenants.tenantapikey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tenants.apiservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'db_table': 'api_usage_logs',
            },
        ),
        migrations.CreateModel(
            name='APIServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'API Service Category',
                'verbose_name_plural': 'API Service Categories',
                'db_table': 'api_service_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apiservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='tenants.apiservicecategory'),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant'),
        ),
        migrations.AddField(
            model_name='apiservice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.CreateModel(
            name='AIAPIKey',
            fields=[
            ],
            options={
                'verbose_name': 'AI API Key',
                'verbose_name_plural': 'AI API Keys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantapikey',),
        ),
        migrations.CreateModel(
            name='SMSAPIKey',
            fields=[
            ],
            options={
                'verbose_name': 'SMS API Key',
                'verbose_name_plural': 'SMS API Keys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantapikey',),
        ),
        migrations.CreateModel(
            name='VideoAPIKey',
            fields=[
            ],
            options={
                'verbose_name': 'Video API Key',
                'verbose_name_plural': 'Video API Keys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantapikey',),
        ),
        migrations.CreateModel(
            name='WhatsAppAPIKey',
            fields=[
            ],
            options={
                'verbose_name': 'WhatsApp API Key',
                'verbose_name_plural': 'WhatsApp API Keys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantapikey',),
        ),
        migrations.CreateModel(
            name='TenantSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('name', models.CharField(max_length=100)),
                ('secret_type', models.CharField(choices=[('database', 'Database Credentials'), ('ssh', 'SSH Keys'), ('certificate', 'SSL Certificate'), ('encryption', 'Encryption Keys'), ('other', 'Other')], max_length=50)),
                ('secret_value', django_cryptography.fields.encrypt(models.TextField())),
                ('secret_value_encrypted', models.BinaryField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rotation_interval_days', models.PositiveIntegerField(default=90, help_text='Days between rotations')),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('can_decrypt_users', models.ManyToManyField(blank=True, help_text='Users who can decrypt this secret', related_name='accessible_secrets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secrets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Tenant Secret',
                'verbose_name_plural': 'Tenant Secrets',
                'db_table': 'tenant_secrets',
                'indexes': [models.Index(fields=['tenant', 'secret_type'], name='tenant_secr_tenant__70bc85_idx'), models.Index(fields=['expires_at'], name='tenant_secr_expires_5033e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenantapikey',
            index=models.Index(fields=['tenant', 'service', 'is_active'], name='tenant_api__tenant__e3d4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantapikey',
            index=models.Index(fields=['tenant', 'is_default'], name='tenant_api__tenant__3beffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantapikey',
            unique_together={('tenant', 'service', 'name')},
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['tenant', 'service', 'created_at'], name='api_usage_l_tenant__39a301_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['created_at'], name='api_usage_l_created_c81af4_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['status_code'], name='api_usage_l_status__582b53_idx'),
        ),
    ]
