# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_apiservice_tenantapikey_apiusagelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='square_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Organization Square Logo'),
        ),
    ]
