# Generated by Django 4.2.7 on 2025-12-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='featuremodule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pricingfeature',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='tenant',
        ),
    ]
