# Generated by Django 4.2.7 on 2025-12-23 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_employmenthistory_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], default='ONBOARDING', max_length=20, verbose_name='Employment Status'),
        ),
    ]
