# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_asset_remove_trainingprogram_cost_per_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='posting_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
