# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='transportallocation',
            name='allocation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Allocation Date'),
        ),
        migrations.AlterField(
            model_name='transportattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
