# Generated by Django 4.2.7 on 2025-12-20 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_initial'),
        ('tenants', '0002_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('CLASSWORK', 'Classwork'), ('PROJECT', 'Project'), ('WORKSHEET', 'Worksheet'), ('ASSESSMENT', 'Assessment'), ('LAB_REPORT', 'Lab Report'), ('OTHER', 'Other')], default='HOMEWORK', max_length=20, verbose_name='Assignment Type')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('max_marks', models.PositiveIntegerField(default=10, help_text='Maximum marks achievable', verbose_name='Maximum Marks')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/resources/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20, verbose_name='Status')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.academicyear', verbose_name='Academic Year')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.schoolclass', verbose_name='Class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Created By (Teacher)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('section', models.ForeignKey(blank=True, help_text='Optional. If empty, applies to all sections of the class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.section', verbose_name='Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject', verbose_name='Subject')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments_assignment',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('submission_text', models.TextField(blank=True, verbose_name='Submission Text')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/', verbose_name='Submission File')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks Obtained')),
                ('teacher_remarks', models.TextField(blank=True, verbose_name='Teacher Remarks')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late Submission'), ('GRADED', 'Graded'), ('RETURNED', 'Returned for Revision'), ('RESUBMITTED', 'Resubmitted')], default='SUBMITTED', max_length=20, verbose_name='Status')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Graded By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student', verbose_name='Student')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'assignments_submission',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_name', 'subject'], name='assignments_class_n_d64122_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_7a9bd6_idx'),
        ),
    ]
