# Generated by Django 4.2.7 on 2025-12-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_resultstatistics_grade_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Issue Date'),
        ),
    ]
